package com.domain;
// Generated May 2, 2015 10:45:47 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Date;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.hibernate.validator.constraints.NotBlank;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name="address"
    ,catalog="revised_cws_db"
)
public class Address  implements java.io.Serializable {

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    private Long id; 
    @OneToMany(fetch=FetchType.LAZY, mappedBy="address")
    private Set<Account> accounts;
    @Column(name="street", length=45)
    private String street;
    @NotEmpty @NotBlank
    @Column(name="brgy", nullable=false, length=45)
    private String brgy;
    @NotNull
    @Column(name="location_code", nullable=false)
    private Integer locationCode;
    @ManyToOne(fetch=FetchType.EAGER, cascade={CascadeType.PERSIST, CascadeType.MERGE})
    @JoinColumn(name="address_group", nullable=false)
    private AddressGroup addressGroup;
    
    public Address() {
    }

    public Address(Set<Account> accounts, String street, String brgy, Integer locationCode, AddressGroup addressGroup) {
        this.accounts = accounts;
        this.street = street;
        this.brgy = brgy;
        this.locationCode = locationCode;
        this.addressGroup = addressGroup;
    }

      
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @JsonBackReference
    public Set getAccounts() {
        return this.accounts;
    }
    
    @JsonProperty
    public void setAcounts(Set<Account> accounts){
        this.accounts = accounts;
    }
    
    public void addAccount(Account account) {
        this.accounts.add(account);
    }
    
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
  
    public String getBrgy() {
        return this.brgy;
    }
    
    public void setBrgy(String brgy) {
        this.brgy = brgy;
    }
    
    @JsonManagedReference
    public AddressGroup getAddressGroup() {
        return addressGroup;
    }

    @JsonProperty
    public void setAddressGroup(AddressGroup addressGroup) {
        this.addressGroup = addressGroup;
    }
    
    public Integer getLocationCode() {
        return this.locationCode;
    }
    
    public void setLocationCode(Integer locationCode) {
        this.locationCode = locationCode;
    }
    
    @Override
    public String toString(){
        return brgy+", "+locationCode;
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder(17, 31). // two randomly chosen prime numbers
                // if deriving: appendSuper(super.hashCode()).
                        append(this.id).
                        toHashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Address other = (Address) obj;
        return new EqualsBuilder().
                append(this.id, other.id).
                isEquals();
    }
}
