package com.domain;
// Generated Apr 16, 2015 12:48:29 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

import javax.validation.Valid;
import javax.validation.constraints.Digits;
import javax.validation.constraints.NotNull;
import java.util.HashSet;
import java.util.Set;

/**
 * MeterReading generated by hbm2java
 */
@Entity
@Table(name="meter_reading")
public class MeterReading extends AuditableEntity implements java.io.Serializable {
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    private Long id;
    @ManyToOne(fetch=FetchType.LAZY, cascade={CascadeType.PERSIST, CascadeType.MERGE})
    @JoinColumn(name="account_id", nullable=false)
    private Account account;
    @Valid
    @ManyToOne(fetch=FetchType.EAGER, cascade={CascadeType.PERSIST, CascadeType.MERGE})
    @JoinColumn(name="schedule_id", nullable=false)
    private Schedule schedule;
    @Digits(fraction=0, integer=10, message = "Invalid input format") @NotNull(message="This field is required")
    @Column(name="reading_value", nullable=false)
    private Integer readingValue;
    @Column(name="consumption", nullable=false)
    private Integer consumption;
    @OneToOne(fetch=FetchType.LAZY, cascade = CascadeType.REMOVE, mappedBy="reading")
    private Invoice invoice;
    @OneToMany(fetch=FetchType.LAZY, cascade = CascadeType.REMOVE, mappedBy = "reading")
    private Set<ModifiedReading> modifiedReadings = new HashSet<>(0);

    public MeterReading() {
    }

    public MeterReading(Account account, Schedule schedule, Integer readingValue, Integer consumption, Invoice invoice) {
        this.account = account;
        this.schedule = schedule;
        this.readingValue = readingValue;
        this.consumption = consumption;
        this.invoice = invoice;
    }
    
    public Long getId() {
        return this.id; 
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    @JsonInclude(value=JsonInclude.Include.NON_EMPTY, content = JsonInclude.Include.NON_EMPTY)
    public Invoice getInvoice() {
        return invoice;
    }

    @JsonProperty
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }

    @JsonManagedReference
    public Account getAccount() {
        return this.account;
    
    }
    @JsonProperty
    public void setAccount(Account account) {
        this.account = account;
    }
    
    @JsonManagedReference
    public Schedule getSchedule() {
        return schedule;
    }
    @JsonProperty
    public void setSchedule(Schedule schedule) {
        this.schedule = schedule;
    }

    public Integer getReadingValue() {
        return this.readingValue;
    }
    
    public void setReadingValue(Integer readingValue) {
        this.readingValue = readingValue;
    }

    public Integer getConsumption() {
        return consumption;
    }

    public void setConsumption(Integer consumption) {
        this.consumption = consumption;
    }

    public Integer getPrevious(){
        return this.readingValue - this.consumption ;
    }

    @JsonBackReference
    public Set<ModifiedReading> getModifiedReadings() {
        return modifiedReadings;
    }

    @JsonProperty
    public void setModifiedReadings(Set<ModifiedReading> modifiedReadings) {
        this.modifiedReadings = modifiedReadings;
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder(17, 31). // two randomly chosen prime numbers
                // if deriving: appendSuper(super.hashCode()).
                        append(this.id).
                        toHashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final MeterReading other = (MeterReading) obj;
        return new EqualsBuilder().
                append(this.id, other.id).
                isEquals();
    }
}