package com.domain;
// Generated May 2, 2015 10:45:47 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonBackReference;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.constraints.NotBlank;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * Occupation generated by hbm`2java
 */
@Entity
@Table(name="occupation"
    ,catalog="revised_cws_db"
)
public class Occupation  implements java.io.Serializable {

    @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="customer"))@Id @GeneratedValue(generator="generator")
    @Column(name="customer_id", unique=true, nullable=false)
    private Long customerId;
    @JsonBackReference
    @OneToOne(fetch=FetchType.LAZY, cascade={CascadeType.PERSIST, CascadeType.MERGE})
    @PrimaryKeyJoinColumn
    private Customer customer;
    @NotEmpty @NotBlank
    @Column(name="position", nullable=false, length=16)
    private String position;
    @NotEmpty @NotBlank
    @Column(name="industry", nullable=false)
    private String industry;

    public Occupation() {
    }

    public Occupation(Customer customer, String position, String industry) {
       this.customer = customer;
       this.position = position;
       this.industry = industry;
    }
   
    
    public Long getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }

    
    
    public String getIndustry() {
        return this.industry;
    }
    
    public void setIndustry(String industry) {
        this.industry = industry;
    }
}


