package com.domain;
// Generated Apr 16, 2015 12:48:29 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Max;
import javax.validation.constraints.NotNull;
import org.hibernate.annotations.Type;
import org.joda.time.DateTime;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name="payment"
    ,catalog="revised_cws_db"
)
public class Payment  implements java.io.Serializable {

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    private Long id;
    @ManyToOne(fetch=FetchType.EAGER, cascade={CascadeType.PERSIST, CascadeType.MERGE})
    @JoinColumn(name="account_id", nullable=false)
    private Account account;
    @OneToOne(fetch=FetchType.EAGER, cascade={CascadeType.PERSIST, CascadeType.MERGE})
    @JoinColumn(name="invoice_id", nullable=false)
    private Invoice invoice;
    @Type(type = "org.jadira.usertype.dateandtime.joda.PersistentDateTime")
    @DateTimeFormat(pattern = "yyyy/MM/dd")
    @Column(name="date", nullable=false, length=10)
    private DateTime date;
    @Digits(fraction=2, integer=10) @NotNull
    @Column(name="amount_paid", nullable=false, precision=10, scale=0)
    private BigDecimal amountPaid;
    @Digits(fraction=2, integer=10) @NotNull
    @Column(name="discount", nullable=false, precision=10, scale=0)
    private BigDecimal discount;
    public Payment() {
    }

    public Payment(Account account, Invoice invoice, DateTime date, BigDecimal amountPaid, BigDecimal discount) {
       this.account = account;
       this.invoice = invoice;
       this.date = date;
       this.amountPaid = amountPaid;
       this.discount = discount;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    @JsonManagedReference
    public Account getAccount() {
        return this.account;
    }
    @JsonProperty
    public void setAccount(Account account) {
        this.account = account;
    }
    @JsonManagedReference
    public Invoice getInvoice() {
        return this.invoice;
    }
    @JsonProperty
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }

    public DateTime getDate() {
        return this.date;
    }
    
    public void setDate(DateTime date) {
        this.date = date;
    }
    
    public BigDecimal getAmountPaid() {
        return this.amountPaid;
    }
    
    public void setAmountPaid(BigDecimal amountPaid) {
        this.amountPaid = amountPaid;
    }

    public BigDecimal getDiscount() {
        return discount;
    }

    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }
}