package com.domain;
// Generated Apr 16, 2015 12:48:29 PM by Hibernate Tools 4.3.1


import com.dao.util.CustomAuditingEntityListener;
import com.dao.util.JsonJodaDateTimeSerializer;
import com.fasterxml.jackson.annotation.*;

import java.math.BigDecimal;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

import javax.validation.constraints.Digits;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.hibernate.annotations.Type;
import org.hibernate.validator.constraints.NotEmpty;
import org.joda.time.DateTime;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name="payment"
    ,catalog="revised_cws_db"
)
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class Payment extends AuditableEntity implements java.io.Serializable {

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    private Long id;
    @ManyToOne(fetch=FetchType.EAGER, cascade={CascadeType.PERSIST, CascadeType.MERGE})
    @JoinColumn(name="account_id", nullable=false)
    private Account account;
    @OneToOne(fetch=FetchType.EAGER, cascade={CascadeType.PERSIST, CascadeType.MERGE})
    @JoinColumn(name="invoice_id", nullable=false)
    private Invoice invoice;
    @Type(type = "org.jadira.usertype.dateandtime.joda.PersistentDateTime")
    @DateTimeFormat(pattern = "yyyy/MM/dd")
    @Column(name="date", nullable=false, length=10)
    private DateTime date;
    @Digits(fraction=2, integer=10, message = "Invalid amount") @NotNull(message="Invalid input")
    @Column(name="amount_paid", nullable=false, precision=10, scale=0) @Min(value=1, message = "Invalid amount")
    private BigDecimal amountPaid;
    @Digits(fraction=2, integer=10, message = "Invalid amount") @NotNull(message="Invalid input")
    @Column(name="discount", nullable=false, precision=10, scale=0)
    private BigDecimal discount;
    @NotEmpty(message = "Invalid OR number")
    @NotNull(message="Invalid OR number") @Pattern(regexp = "[\\s]*[0-9]*[1-9]+",message="Invalid OR number")
    @Column(name="or_number", nullable = false)
    private String receiptNumber;
    public Payment() {
    }

    public Payment(Account account, Invoice invoice, DateTime date, BigDecimal amountPaid, BigDecimal discount, String receiptNumber) {
       this.account = account;
       this.invoice = invoice;
       this.date = date;
       this.amountPaid = amountPaid;
       this.discount = discount;
        this.receiptNumber = receiptNumber;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    @JsonManagedReference
    public Account getAccount() {
        return this.account;
    }
    @JsonProperty
    public void setAccount(Account account) {
        this.account = account;
    }
    //@JsonManagedReference
    public Invoice getInvoice() {
        return this.invoice;
    }
    @JsonProperty
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }

    public DateTime getDate() {
        return this.date;
    }
    
    public void setDate(DateTime date) {
        this.date = date;
    }
    
    public BigDecimal getAmountPaid() {
        return this.amountPaid;
    }
    
    public void setAmountPaid(BigDecimal amountPaid) {
        this.amountPaid = amountPaid;
    }

    public BigDecimal getDiscount() {
        return discount;
    }

    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    public String getReceiptNumber() { return receiptNumber; }

    public void setReceiptNumber(String receiptNumber) {
        this.receiptNumber = receiptNumber;
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder(17, 31). // two randomly chosen prime numbers
                // if deriving: appendSuper(super.hashCode()).
                        append(this.id).
                        toHashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Payment other = (Payment) obj;
        return new EqualsBuilder().
                append(this.id, other.id).
                isEquals();
    }
}